name: CI

on:
  push:	
    branches:	
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      with:
        node-version: 12.8
      uses: actions/setup-node@v1.1.0
    - name: npm install build, and test
      run: |
        npm ci
        npm run lint
        npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
        npm run build -- --prod --progress=false --base-href "/angular-sample/"
    - name: Deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: dist/angular-sample
        SCRIPT_MODE: true
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        bash ./entrypoint.sh
