name: CI

on:
  push:	
    branches:	
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      with:
        node-version: 12.8
      uses: actions/setup-node@v1.1.0
    - name: npm install build, and test
      run: |
        npm ci
        npm run lint
        npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
        npm run build -- --prod --progress=false --base-href "/angular-sample/"
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/angular-sample
